"""Domain models for tasks, traces, and reports.

These data classes are long-stable: they define the shape of data persisted
by TaskRepository implementations across M1 (InMemory) and M4 (SQLite).
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Literal

from pydantic import BaseModel, Field

TaskStatus = Literal["pending", "running", "completed", "failed"]


def _utc_now() -> datetime:
    """Return current UTC time. Helper for default factories."""
    return datetime.now(tz=UTC)


class Task(BaseModel):
    """A diagnostic task submitted via POST /api/v1/tasks (M1+).

    M0 defines the model only; the route and persistence land in M1.
    """

    task_id: str = Field(description="UUID4 string, generated by the API layer.")
    repository_path: str = Field(description="Canonicalized absolute path of the input repository.")
    issue_description: str = Field(
        description="Natural-language problem description, 10-2000 chars."
    )
    error_log: str | None = Field(
        default=None, description="Optional error log text, max 10000 chars."
    )
    status: TaskStatus = Field(default="pending")
    submitted_at: datetime = Field(default_factory=_utc_now)
    started_at: datetime | None = Field(default=None)
    finished_at: datetime | None = Field(default=None)
    current_node: str | None = Field(
        default=None, description="Most recent node name during execution."
    )


class Trace(BaseModel):
    """A single tool-call or node-timing record persisted to the trace store.

    Two trace kinds are stored:

    - ``tool_call``: a single tool invocation (mirrors ToolCall fields).
    - ``node_timing``: a node's start/end/duration.

    M0 defines the model only; persistence and Tracer implementation land in M1.
    """

    task_id: str
    kind: Literal["tool_call", "node_timing"]
    recorded_at: datetime = Field(default_factory=_utc_now)
    payload: dict[str, object] = Field(
        description="Typed payload; structure depends on ``kind``.",
    )


class Report(BaseModel):
    """The diagnostic report produced by the Agent.

    M0 defines the model only. The report content shape will be filled in M1
    (basic_report + markdown_report) and extended in M2 (root_causes).
    """

    task_id: str
    json_report: dict[str, object] = Field(
        description="Structured report. M1: basic summary. M2: adds root_causes.",
    )
    markdown_report: str = Field(description="Human-readable Markdown report.")
    created_at: datetime = Field(default_factory=_utc_now)
